# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 09:18
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField(default=5)),
                ('time', models.DateTimeField()),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PR', 'Private'), ('CO', 'Contracted')], default='PR', max_length=2)),
                ('biography', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('activated', models.BooleanField(default=True)),
                ('course_code_set', models.ManyToManyField(related_name='tutor_set', related_query_name='tutor_set', to='tutoriaapi.CourseCode')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='user', related_query_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=8)),
                ('avatar', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', related_query_name='wallet', to='tutoriaapi.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutorial', related_query_name='tutorial', serialize=False, to='tutoriaapi.Event')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('tutoriaapi.event',),
        ),
        migrations.CreateModel(
            name='UnavailablePeriod',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='unavailable_period', related_query_name='unavailable_period', serialize=False, to='tutoriaapi.Event')),
            ],
            bases=('tutoriaapi.event',),
        ),
        migrations.AddField(
            model_name='tutor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_set', related_query_name='tutor_set', to='tutoriaapi.University'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', related_query_name='tutor', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transaction_set', related_query_name='deposit_transaction', to='tutoriaapi.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_transaction_set', related_query_name='withdraw_transaction', to='tutoriaapi.Wallet'),
        ),
        migrations.AddField(
            model_name='subjecttag',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tag_set', related_query_name='subject_tag_set', to='tutoriaapi.Tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', related_query_name='student', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receive_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_message_set', related_query_name='receive_message', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_message_set', related_query_name='send_message', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='user_set',
            field=models.ManyToManyField(related_name='event_set', related_query_name='event', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_code_set', related_query_name='course_code', to='tutoriaapi.University'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', related_query_name='company', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='unavailableperiod',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_period_set', related_query_name='unavailable_period_set', to='tutoriaapi.Tutor'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='company_to_student_transaction',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_tutorial_company_to_student', related_query_name='reason_tutorial_company_to_student', to='tutoriaapi.Transaction'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='company_to_tutor_transaction',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_tutorial_company_to_tutor', related_query_name='reason_tutorial_company_to_tutor', to='tutoriaapi.Transaction'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='coupon',
            field=models.ManyToManyField(related_name='tutorial_set', related_query_name='tutorial', to='tutoriaapi.Coupon'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_set', related_query_name='tutorial', to='tutoriaapi.Student'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='student_to_company_transaction',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_tutorial_student_to_company', related_query_name='reason_tutorial_student_to_company', to='tutoriaapi.Transaction'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_set', related_query_name='tutorial', to='tutoriaapi.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='tutoriaapi.Tutorial'),
        ),
    ]
