# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:46
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField(default=5)),
                ('creationDate', models.DateTimeField()),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=8)),
                ('avatar', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='student', related_query_name='student', serialize=False, to='tutoriaapi.Role')),
            ],
            bases=('tutoriaapi.role',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutor', related_query_name='tutor', serialize=False, to='tutoriaapi.Role')),
                ('type', models.CharField(choices=[('PR', 'Private'), ('CO', 'Contracted')], default='PR', max_length=2)),
                ('biography', models.TextField()),
                ('hourlyRate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('activated', models.BooleanField(default=True)),
                ('courseCodeSet', models.ManyToManyField(related_name='tutorSet', related_query_name='tutorSet', to='tutoriaapi.CourseCode')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorSet', related_query_name='tutorSet', to='tutoriaapi.University')),
            ],
            bases=('tutoriaapi.role',),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutorial', related_query_name='tutorial', serialize=False, to='tutoriaapi.Event')),
                ('locked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorialSet', related_query_name='tutorialSet', to='tutoriaapi.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorialSet', related_query_name='tutorialSet', to='tutoriaapi.Tutor')),
            ],
            bases=('tutoriaapi.event',),
        ),
        migrations.CreateModel(
            name='UnavailablePeriod',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='unavailablePeriod', related_query_name='unavailablePeriod', serialize=False, to='tutoriaapi.Event')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailablePeriodSet', related_query_name='unavailablePeriodSet', to='tutoriaapi.Tutor')),
            ],
            bases=('tutoriaapi.event',),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleSet', related_query_name='roleSet', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='userSet',
            field=models.ManyToManyField(related_name='eventSet', related_query_name='eventSet', to='tutoriaapi.User'),
        ),
        migrations.AddField(
            model_name='subjecttag',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTagSet', related_query_name='subjectTagSet', to='tutoriaapi.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='tutoriaapi.Tutorial'),
        ),
    ]
