# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0002_occupiedsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackenOutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupiedSession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blackenOutSession', related_query_name='blackenOutSession', to='tutoriaapi.OccupiedSession')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupiedSession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialSession', related_query_name='tutorialSession', to='tutoriaapi.OccupiedSession')),
            ],
        ),
    ]
