# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0002_auto_20171101_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='baseUser',
            new_name='base_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
