# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0003_auto_20171102_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='hourlyRate',
            new_name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='courseCodeSet',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course_code_set',
            field=models.ManyToManyField(related_name='tutor_set', related_query_name='tutor_set', to='tutoriaapi.CourseCode'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_set', related_query_name='role_set', to='tutoriaapi.User'),
        ),
        migrations.AlterField(
            model_name='subjecttag',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tag_set', related_query_name='subject_tag_set', to='tutoriaapi.Tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_set', related_query_name='tutor_set', to='tutoriaapi.University'),
        ),
    ]
