# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0003_blackenoutsession_tutorialsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupiedsession',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occupiedsession',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 7, 40, 36, 683297, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupiedsession',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 7, 40, 43, 414380, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
