# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0004_auto_20171030_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackenoutsession',
            name='tutorRole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blackenOutSession', related_query_name='blackenOutSession', to='tutoriaapi.TutorRole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialsession',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorialsession',
            name='studentRole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialSessions', related_query_name='tutorialSessions', to='tutoriaapi.StudentRole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialsession',
            name='tutorRole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialSessions', related_query_name='tutorialSessions', to='tutoriaapi.TutorRole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
