# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0004_auto_20171102_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
