# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0005_auto_20171030_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRoleSubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tutorrole',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorrole',
            name='type',
            field=models.CharField(choices=[('PR', 'Private'), ('CO', 'Contracted')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleSet', related_query_name='roleSet', to='tutoriaapi.UserProfile'),
        ),
        migrations.AddField(
            model_name='tutorrolesubjecttag',
            name='tutorRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTagSet', related_query_name='subjectTagSet', to='tutoriaapi.TutorRole'),
        ),
        migrations.AddField(
            model_name='tutorrole',
            name='courseCode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='tutorRoleSet', related_query_name='tutorRoleSet', to='tutoriaapi.CourseCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrole',
            name='university',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='tutorRoleSet', related_query_name='tutorRoleSet', to='tutoriaapi.University'),
            preserve_default=False,
        ),
    ]
