# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0005_auto_20171102_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='userSet',
        ),
        migrations.AddField(
            model_name='event',
            name='user_set',
            field=models.ManyToManyField(related_name='event_set', related_query_name='event_set', to='tutoriaapi.User'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_set', related_query_name='tutorial_set', to='tutoriaapi.Student'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_set', related_query_name='tutorial_set', to='tutoriaapi.Tutor'),
        ),
        migrations.AlterField(
            model_name='unavailableperiod',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='unavailable_period', related_query_name='unavailable_period', serialize=False, to='tutoriaapi.Event'),
        ),
        migrations.AlterField(
            model_name='unavailableperiod',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_period_set', related_query_name='unavailable_period_set', to='tutoriaapi.Tutor'),
        ),
    ]
