# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0006_auto_20171030_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AlterField(
            model_name='tutorrole',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
