# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0007_auto_20171030_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupiedsession',
            old_name='user',
            new_name='userProfileSet',
        ),
        migrations.RemoveField(
            model_name='blackenoutsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentrole',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutorialsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutorrole',
            name='id',
        ),
        migrations.AlterField(
            model_name='blackenoutsession',
            name='occupiedSession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='blackenOutSession', related_query_name='blackenOutSession', serialize=False, to='tutoriaapi.OccupiedSession'),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='studentRole', related_query_name='studentRole', serialize=False, to='tutoriaapi.Role'),
        ),
        migrations.AlterField(
            model_name='tutorialsession',
            name='occupiedSession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutorialSession', related_query_name='tutorialSession', serialize=False, to='tutoriaapi.OccupiedSession'),
        ),
        migrations.AlterField(
            model_name='tutorialsession',
            name='studentRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorialSessions', related_query_name='tutorialSessions', to='tutoriaapi.StudentRole'),
        ),
        migrations.AlterField(
            model_name='tutorialsession',
            name='tutorRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorialSessions', related_query_name='tutorialSessions', to='tutoriaapi.TutorRole'),
        ),
        migrations.AlterField(
            model_name='tutorrole',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutorRole', related_query_name='tutorRole', serialize=False, to='tutoriaapi.Role'),
        ),
    ]
