# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriaapi', '0008_auto_20171030_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackenoutsession',
            name='tutorRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackenOutSessionSet', related_query_name='blackenOutSessionSet', to='tutoriaapi.TutorRole'),
        ),
    ]
